export const toolPaths = [
  'dropbox-s-public-workspace/dropbox-api-reference/add-file-member.js',
  'dropbox-s-public-workspace/dropbox-api-reference/add-folder-member.js',
  'dropbox-s-public-workspace/dropbox-api-reference/app.js',
  'dropbox-s-public-workspace/dropbox-api-reference/check-job-status.js',
  'dropbox-s-public-workspace/dropbox-api-reference/check-remove-member-job-status.js',
  'dropbox-s-public-workspace/dropbox-api-reference/check-share-job-status.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/copy-batch-check.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/copy-batch.js',
  'dropbox-s-public-workspace/dropbox-api-reference/copy-reference-get.js',
  'dropbox-s-public-workspace/dropbox-api-reference/copy-reference-save.js',
  'dropbox-s-public-workspace/dropbox-api-reference/copy.js',
  'dropbox-s-public-workspace/dropbox-api-reference/count.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/create-folder-batch-check.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/create-folder-batch.js',
  'dropbox-s-public-workspace/dropbox-api-reference/create-folder.js',
  'dropbox-s-public-workspace/dropbox-api-reference/create.js',
  'dropbox-s-public-workspace/dropbox-api-reference/delete-all-closed.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/delete-batch.js',
  'dropbox-s-public-workspace/dropbox-api-reference/delete.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/download-zip.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/download.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/export.js',
  'dropbox-s-public-workspace/dropbox-api-reference/features-get-values.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/get-account-batch.js',
  'dropbox-s-public-workspace/dropbox-api-reference/get-account.js',
  'dropbox-s-public-workspace/dropbox-api-reference/get-current-account.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/get-file-lock-batch.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/get-file-metadata-batch.js',
  'dropbox-s-public-workspace/dropbox-api-reference/get-file-metadata.js',
  'dropbox-s-public-workspace/dropbox-api-reference/get-folder-metadata.js',
  'dropbox-s-public-workspace/dropbox-api-reference/get-info.js',
  'dropbox-s-public-workspace/dropbox-api-reference/get-metadata.js',
  'dropbox-s-public-workspace/dropbox-api-reference/get-preview.js',
  'dropbox-s-public-workspace/dropbox-api-reference/get-shared-link-file.js',
  'dropbox-s-public-workspace/dropbox-api-reference/get-shared-link-metadata.js',
  'dropbox-s-public-workspace/dropbox-api-reference/get-space-usage.js',
  'dropbox-s-public-workspace/dropbox-api-reference/get-temporary-link.js',
  'dropbox-s-public-workspace/dropbox-api-reference/get-temporary-upload-link.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/get-thumbnail-batch.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/get-thumbnail.js',
  'dropbox-s-public-workspace/dropbox-api-reference/get-user-folders.js',
  'dropbox-s-public-workspace/dropbox-api-reference/get.js',
  'dropbox-s-public-workspace/dropbox-api-reference/groups-create.js',
  'dropbox-s-public-workspace/dropbox-api-reference/groups-delete.js',
  'dropbox-s-public-workspace/dropbox-api-reference/groups-get-info.js',
  'dropbox-s-public-workspace/dropbox-api-reference/groups-job-status-get.js',
  'dropbox-s-public-workspace/dropbox-api-reference/groups-list-continue.js',
  'dropbox-s-public-workspace/dropbox-api-reference/groups-list.js',
  'dropbox-s-public-workspace/dropbox-api-reference/groups-members-add.js',
  'dropbox-s-public-workspace/dropbox-api-reference/groups-members-list-continue.js',
  'dropbox-s-public-workspace/dropbox-api-reference/groups-members-list.js',
  'dropbox-s-public-workspace/dropbox-api-reference/groups-members-remove.js',
  'dropbox-s-public-workspace/dropbox-api-reference/groups-members-set-access-type.js',
  'dropbox-s-public-workspace/dropbox-api-reference/groups-update.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/legal-holds-create-policy.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/legal-holds-get-policy.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/legal-holds-list-held-revisions-continue.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/legal-holds-list-held-revisions.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/legal-holds-list-policies.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/legal-holds-release-policy.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/legal-holds-update-policy.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/linked-apps-list-member-linked-apps.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/linked-apps-list-members-linked-apps.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/linked-apps-revoke-linked-app-batch.js',
  'dropbox-s-public-workspace/dropbox-api-reference/linked-apps-revoke-linked-app.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-continue.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/list-file-members-batch.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-file-members-continue.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-file-members.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-folder-continue.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-folder-get-latest-cursor.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-folder-longpoll.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-folder-members-continue.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-folder.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-folders-continue.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-folders.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-mountable-folders-continue.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-mountable-folders.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-received-files-continue.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-received-files.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-revisions.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list-shared-links.js',
  'dropbox-s-public-workspace/dropbox-api-reference/list.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/lock-file-batch.js',
  'dropbox-s-public-workspace/dropbox-api-reference/member-space-limits-excluded-users-add.js',
  'dropbox-s-public-workspace/dropbox-api-reference/member-space-limits-excluded-users-list-continue.js',
  'dropbox-s-public-workspace/dropbox-api-reference/member-space-limits-excluded-users-list.js',
  'dropbox-s-public-workspace/dropbox-api-reference/member-space-limits-excluded-users-remove.js',
  'dropbox-s-public-workspace/dropbox-api-reference/member-space-limits-get-custom-quota.js',
  'dropbox-s-public-workspace/dropbox-api-reference/member-space-limits-remove-custom-quota.js',
  'dropbox-s-public-workspace/dropbox-api-reference/member-space-limits-set-custom-quota.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-add-job-status-get.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-add.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-delete-profile-photo.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-get-info.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-list-continue.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-list.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-move-former-member-files-job-status-check.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-move-former-member-files.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-recover.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-remove-job-status-get.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-remove.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-secondary-emails-add.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-secondary-emails-delete.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-secondary-emails-resend-verification-emails.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-send-welcome-email.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-set-admin-permissions.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-set-profile-photo.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-set-profile.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-suspend.js',
  'dropbox-s-public-workspace/dropbox-api-reference/members-unsuspend.js',
  'dropbox-s-public-workspace/dropbox-api-reference/modify-shared-link-settings.js',
  'dropbox-s-public-workspace/dropbox-api-reference/mount-folder.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/move-batch-check.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/move-batch.js',
  'dropbox-s-public-workspace/dropbox-api-reference/move.js',
  'dropbox-s-public-workspace/dropbox-api-reference/namespaces-list-continue.js',
  'dropbox-s-public-workspace/dropbox-api-reference/namespaces-list.js',
  'dropbox-s-public-workspace/dropbox-api-reference/permanently-delete.js',
  'dropbox-s-public-workspace/dropbox-api-reference/properties-add.js',
  'dropbox-s-public-workspace/dropbox-api-reference/properties-overwrite.js',
  'dropbox-s-public-workspace/dropbox-api-reference/properties-remove.js',
  'dropbox-s-public-workspace/dropbox-api-reference/properties-search-continue.js',
  'dropbox-s-public-workspace/dropbox-api-reference/properties-search.js',
  'dropbox-s-public-workspace/dropbox-api-reference/relinquish-file-membership.js',
  'dropbox-s-public-workspace/dropbox-api-reference/relinquish-folder-membership.js',
  'dropbox-s-public-workspace/dropbox-api-reference/remove-file-member-2.js',
  'dropbox-s-public-workspace/dropbox-api-reference/remove-folder-member.js',
  'dropbox-s-public-workspace/dropbox-api-reference/restore.js',
  'dropbox-s-public-workspace/dropbox-api-reference/revoke-shared-link.js',
  'dropbox-s-public-workspace/dropbox-api-reference/save-url-check-job-status.js',
  'dropbox-s-public-workspace/dropbox-api-reference/save-url.js',
  'dropbox-s-public-workspace/dropbox-api-reference/search-continue.js',
  'dropbox-s-public-workspace/dropbox-api-reference/search.js',
  'dropbox-s-public-workspace/dropbox-api-reference/set-access-inheritance.js',
  'dropbox-s-public-workspace/dropbox-api-reference/set-profile-photo.js',
  'dropbox-s-public-workspace/dropbox-api-reference/share-folder.js',
  'dropbox-s-public-workspace/dropbox-api-reference/team-folder-activate.js',
  'dropbox-s-public-workspace/dropbox-api-reference/team-folder-archive-check.js',
  'dropbox-s-public-workspace/dropbox-api-reference/team-folder-archive.js',
  'dropbox-s-public-workspace/dropbox-api-reference/team-folder-create.js',
  'dropbox-s-public-workspace/dropbox-api-reference/team-folder-get-info.js',
  'dropbox-s-public-workspace/dropbox-api-reference/team-folder-list-continue.js',
  'dropbox-s-public-workspace/dropbox-api-reference/team-folder-list.js',
  'dropbox-s-public-workspace/dropbox-api-reference/team-folder-permanently-delete.js',
  'dropbox-s-public-workspace/dropbox-api-reference/team-folder-rename.js',
  'dropbox-s-public-workspace/dropbox-api-reference/team-folder-update-sync-settings.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/templates-add-for-team.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/templates-get-for-team.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/templates-get-for-user.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/templates-list-for-team.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/templates-list-for-user.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/templates-remove-for-team.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/templates-remove-for-user.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/templates-update-for-team.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/templates-update-for-user.js',
  'dropbox-s-public-workspace/dropbox-api-reference/token-from-oauth-1.js',
  'dropbox-s-public-workspace/dropbox-api-reference/token-get-authenticated-admin.js',
  'dropbox-s-public-workspace/dropbox-api-reference/token-revoke.js',
  'dropbox-s-public-workspace/dropbox-api-reference/transfer-folder.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/unlock-file-batch.js',
  'dropbox-s-public-workspace/dropbox-api-reference/unmount-folder.js',
  'dropbox-s-public-workspace/dropbox-api-reference/unshare-file.js',
  'dropbox-s-public-workspace/dropbox-api-reference/unshare-folder.js',
  'dropbox-s-public-workspace/dropbox-api-reference/update-file-member.js',
  'dropbox-s-public-workspace/dropbox-api-reference/update-folder-member.js',
  'dropbox-s-public-workspace/dropbox-api-reference/update-folder-policy.js',
  'dropbox-s-public-workspace/dropbox-api-reference/update.js',
  'dropbox-s-public-workspace/dropbox-api-reference/upload-session-append.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/upload-session-finish-batch-check.js',
  // 'dropbox-s-public-workspace/dropbox-api-reference/upload-session-finish-batch.js',
  'dropbox-s-public-workspace/dropbox-api-reference/upload-session-finish.js',
  'dropbox-s-public-workspace/dropbox-api-reference/upload-session-start.js',
  'dropbox-s-public-workspace/dropbox-api-reference/upload.js',
  'dropbox-s-public-workspace/dropbox-api-reference/user.js',
  'dropbox-s-public-workspace/dropbox-team-admin-workflows/add-group.js',
  'dropbox-s-public-workspace/dropbox-team-admin-workflows/add-member-to-group.js',
  'dropbox-s-public-workspace/dropbox-team-admin-workflows/add-member-to-team.js',
  'dropbox-s-public-workspace/dropbox-team-admin-workflows/get-groups.js',
  'dropbox-s-public-workspace/dropbox-team-admin-workflows/get-more-groups.js',
  'dropbox-s-public-workspace/dropbox-team-admin-workflows/remove-member.js',
  'dropbox-s-public-workspace/dropbox-team-admin-workflows/suspend-member.js',
  'dropbox-s-public-workspace/dropbox-team-admin-workflows/unsuspend-member.js',
];